### ISSUE TITLE
Can't import SEAnim in blender 2.81

### ISSUE THREAD

**Issue by laluv193** [SE2Dev/io_anim_seanim#32] opened 2020-11-21 01:11 UTC
the import button in gray, meaning that I cannot import my SEAnim file. It says that ADDITIVE animation is not supported, but why?
If anyone has any answer I would be very glad. Thank you.

**Comment by SE2Dev** [comment] 2020-11-21 02:41
This is a duplicate of #8

**Closed by SE2Dev** 2020-11-21 02:41 UTC
