### ISSUE TITLE
ADDITIVE animations are not supported

### ISSUE THREAD

**Issue by ghost** [SE2Dev/io_anim_seanim#16] opened 2019-07-23 00:37 UTC
"ADDITIVE animations are not implemented at this time" I tried all branches and still doesn't work

**Comment by rdlady** [comment] 2019-08-03 09:35
I have the same issue.

**Comment by SE2Dev** [comment] 2019-08-03 11:49
This is because additive animations are not currently supported. I have no reference for how they are supposed to look in a traditional animation environment, therefore I have no way of knowing how they should be implemented.

**Comment by KenzG** [comment] 2019-08-14 11:24
Still, I read about this updated 3 days ago but ADDITIVE animations still not working currently

**Comment by SE2Dev** [comment] 2019-08-14 11:34
Correct, they're still not supported.

Like I said before, until I have an official reference for how additive animations should look or are edited in traditional workflows, I can't properly implement support for them.

**Comment by KenzG** [comment] 2019-08-14 11:40
> Correct, they're still not supported. Like I said before, until I have an official reference for how additive animations should look or are edited in traditional workflows, I can't properly implement support for them.
> […](#)
> On Aug 14, 2019, at 7:24 AM, KenzG ***@***.***> wrote: Still, I read about this updated 3 days ago but ADDITIVE animations still not working currently — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

But yeah, I'm somewhat happy to see this Updated because been waiting for a long time.

**Comment by SE2Dev** [comment] 2020-11-21 02:42
Duplicate of #8

**Closed by SE2Dev** 2020-11-21 02:42 UTC
