### ISSUE TITLE
SEanim additve animations are not currenly supported Version0.4.1 on Blender 2.90.1

### ISSUE THREAD

**Issue by GamingNexus1** [SE2Dev/io_anim_seanim#30] opened 2020-11-03 18:43 UTC
what can i do to fix the error?

**Comment by SE2Dev** [comment] 2020-11-06 15:38
There's nothing either of us can do right now. They have a lot of fundamental differences from other types of animations, and I have no reference for how they're supposed to look in-editor.

It's not possible to implement support for them at this time.

**Comment by SE2Dev** [comment] 2020-11-21 02:42
Duplicate of #8

**Closed by SE2Dev** 2020-11-21 02:42 UTC
